# Based on the template at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Terraform.gitlab-ci.yml

include:
  - local: templates/tf/Base.latest.gitlab-ci.yml
  # See https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Terraform/

stages:
  - validate
  - test
  - build
  - deploy
  - configure
  - cleanup

fmt:
  extends: .terraform:fmt
  needs: []

validate:
  extends: .terraform:validate
  needs: []

build:
  before_script:
    - export TF_VAR_common_token_name=$COMMON_REPO_TOKEN_NAME
    - export TF_VAR_common_token_pass=$COMMON_REPO_TOKEN_PASS
  extends: .terraform:build

deploy:
  extends: .terraform:deploy
  dependencies:
    - build
  environment:
    name: $TF_STATE_NAME
  artifacts:
    name: bolt-inventory
    paths:
      - ${TF_ROOT}/bolt-inventory.yaml

tfsec:
  image: aquasec/tfsec:v1.28.0
  stage: validate
  script:
    - cd "${TF_ROOT}"
    - /usr/bin/tfsec
  allow_failure: false
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_OPEN_MERGE_REQUESTS  # Don't add it to a *branch* pipeline if it's already in a merge request pipeline.
      when: never
    - if: $CI_COMMIT_BRANCH        # If there's no open merge request, add it to a *branch* pipeline instead.

terrascan:
  image: tenable/terrascan
  stage: validate
  script:
    - terrascan scan -i terraform --iac-version v14 --iac-dir ${TF_ROOT} --non-recursive --skip-rules=AC_AWS_0369
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_OPEN_MERGE_REQUESTS  # Don't add it to a *branch* pipeline if it's already in a merge request pipeline.
      when: never
    - if: $CI_COMMIT_BRANCH        # If there's no open merge request, add it to a *branch* pipeline instead.

check_compliance:
  image: eerkunt/terraform-compliance
  stage: validate
  allow_failure: true
  before_script:
    - export TF_VAR_common_token_name=$COMMON_REPO_TOKEN_NAME
    - export TF_VAR_common_token_pass=$COMMON_REPO_TOKEN_PASS
  script:
    - mkdir tempdir
    - cd tempdir
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@bbpgitlab.epfl.ch/cs/cloud/aws/terraform-compliance
    - ls -la terraform-compliance
    - cp ../*.tf ../*.tmpl .
    - rm -f gitlab-config.tf
    - terraform init
    - terraform plan -out=plan.tfplan > /dev/null && terraform show -json plan.tfplan > plan.json
    - terraform-compliance -f ./terraform-compliance -p ./plan.json

#puppet_bolt:
#  image: puppet/puppet-bolt
#  stage: configure
#  resource_group: ${TF_STATE_NAME}
#  dependencies:
#    - deploy
#  rules:
#    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#  script:
#    - cat bolt-inventory.yaml
#    - bolt plan show aws_poc -v
#    - bolt plan run aws_poc -v
  
  
